spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digilo
    username: riakgu
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000ms

logging:
  level:
    org.hibernate.SQL: debug
