spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digilo
    username: riakgu
    password: secret
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000ms

jwt:
  access-secret: dev-access-secret
  access-expiration: 86400000
  refresh-secret: dev-refresh-secret
  refresh-expiration: 604800000
  issuer: digilo

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug
